<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <Authors>Damian Suess</Authors>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <Import Project="../../build/SampleApp.props" />

  <ItemGroup>
    <PackageReference Include="Avalonia.Fonts.Inter" />
  </ItemGroup>
  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  
  <ItemGroup>
    <AvaloniaResource Remove="Models\**" />
    <AvaloniaXaml Remove="Models\**" />
    <Compile Remove="Models\**" />
    <EmbeddedResource Remove="Models\**" />
    <None Remove="Models\**" />
  </ItemGroup>

</Project>
